Initial project structure
kiran-anand14/async-comm pull request #1
Opened 2021-04-29 16:35 UTC by parvez0

I have build generic functions and have installed required packages like config manager, logger etc

2021-04-30 06:07 UTC, kiran-anand14 commented on app/broker.go
> +
I am sending you directory structure on upwork chat. Please organize code accordingly and then refloat.
I have already created some basic files in the structure and you can created additional go files, and then add all the functions that I had listed in the document in appropriate files in the directory structure, even if you have not implemented the function, add it in appropriate file and keep its implementation blank.

2021-04-30 06:09 UTC, kiran-anand14 commented on app/broker.go
> +
And I hope producer consumer application is to be written yet as per the requirements in the doc. So, I am commenting on the functionality at this moment.

2021-04-30 06:10 UTC, kiran-anand14 commented on config.yml
> +# redis connection information
Will this be act as an input to Docker containers?

2021-04-30 06:52 UTC, kiran-anand14 commented on main.go
> +
main.go is for applications, check my directory structure.

2021-04-30 07:27 UTC, kiran-anand14 commented on pkg/redis.go
> +		return err
General: Complete code should have error logs at appropriate places so that if error is returned, user should be able look for errors in the log file.

Complete code should have debug logs at appropriate places for efficiently debugging the failures.

2021-04-30 07:34 UTC, kiran-anand14 commented on pkg/redis.go
> +func (r *Redis) Consume(ch chan Packet, ru Routine) {
Why consumer is infinitely running, it will be invoked only when some application (like asynccommtest app) will call pull() function. On pull, it will return give the message to consumer routine which had called this function. Once consumer will finish the processing, it will call ack() function to instruct the asyncomm library to send ack.

I am emphasizing again, try to stick to what is written in the requirements document. Read each and every functionality carefully and if in any doubt, discuss with me. If you think any enhancement is needed and worth discuss, then also discuss with me.

I am stopping code review at this point, I think first go through the directory structure and incorporate the comments given till now. You might have questions for me.

2021-04-30 07:38 UTC, kiran-anand14 requested changes
I have not reviewed the functionality, but have comments in general. Please have a look at the comments and directory structure floated in the chat.

2021-05-03 15:29 UTC, kiran-anand14 commented on build/package/asynccommtest/Dockerfile
> +RUN go build -o /go/bin/asynccomm ./internal/app/asynccommtest
Only binary should be present in the Docker image, not the code.

2021-05-03 15:41 UTC, parvez0 commented on build/package/asynccommtest/Dockerfile
> +RUN go build -o /go/bin/asynccomm ./internal/app/asynccommtest
Yes that's what that container is doing, it will work in 2 steps first it will build the executable and then package the executable in next step, so if you login into a running container you will not see any errors

2021-05-03 15:46 UTC, kiran-anand14 commented on build/package/asynccommtest/Dockerfile
> +COPY ../../../config.yml /etc/async-comm
Don't copy config at Docker image building time. At run time, a host volume should be mounted where this file should be present and binary should look file from this mounted path.

2021-05-03 15:56 UTC, parvez0 commented on build/package/asynccommtest/Dockerfile
> +COPY ../../../config.yml /etc/async-comm
made the change

2021-05-04 06:02 UTC, kiran-anand14 commented on pkg/asynccomm/ac_logger/formatter.go
> +package ac_logger
don't use _ in the folder names. Rather than ac_logger, simply use logger.

2021-05-04 06:07 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +	rdb := redis.NewRdb(ctx, opts.Redis.Host, opts.Redis.Port, opts.Redis.Username, opts.Redis.Password, log)
Does it return any error?

2021-05-04 06:13 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +const DefaultConsumerGroup = "-consumer-group"
Consumer Group is a concept of Redis, so it should go in redis package.

2021-05-04 07:32 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +}
Why is this function provided by asynccomm library? Function RegisterConsumer in our redis package should take care of all Redis related requirements to manage producer and consumer.

2021-05-04 07:37 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +	rdb := redis.NewRdb(ctx, opts.Redis.Host, opts.Redis.Port, opts.Redis.Username, opts.Redis.Password, log)
As we discussed, initialization of our redis package should be done in main.go of the application and the handle of RDB connection should be passed to asynccomm library on calling NewAC

2021-05-04 07:38 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +}
This function will not be done as mentioned in above comment because NewAC() would be sufficient.

2021-05-04 07:42 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) Push(q string, msg []byte) (string, error) {
Is it returning msg id as a string?

2021-05-04 08:02 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +	return nil
As a thumb rule, Redis specific functionality should be in redis.go, it should not be part of asynccomm.

2021-05-04 08:03 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +	return ac.Rdb.Consume(ctx, q, q + DefaultConsumerGroup, consumer)
Again DefaultConsumerGroup is Redis specific functionality.

2021-05-04 08:09 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +	exits := ac.Rdb.StreamExits(q)
Typo - Change function name and related variable comments. I think you meant StreamExists.

2021-05-04 08:14 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +	}
Why are you adding a meesage - "initial message"? If you think that before creating a ConsumerGrp, a queue must exist, then can you delete this message from queue or pull this msg from queue immediately after it is added?

2021-05-04 08:19 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) ClaimPendingMessages(q, consumer string) error {
This function should go in redis.go. And Pull() function in asynccomm library should call this function as per Appendix A in the document. Please re-read Appendix A, it says that every consumer will try to claim pending messages on every pull if certain time has elasped.

2021-05-04 08:20 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +	return nil
Again code should go in redis.go

2021-05-04 08:24 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) CreateQ(q string) error {
Can you add persistence argument as mentioned in the document? If persistence of streams is not supported across reboots of Redis nodes, then if a user call CreateQ function with persistence as true, just return with error that PERSISTENCE_IS_NOT_SUPPORTED.

2021-05-04 08:25 UTC, parvez0 commented on pkg/asynccomm/ac_logger/formatter.go
> +package ac_logger
made the change

2021-05-04 08:26 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +	rdb := redis.NewRdb(ctx, opts.Redis.Host, opts.Redis.Port, opts.Redis.Username, opts.Redis.Password, log)
no it doesn't, it gave us a onConnect function where we have to handle connection and disconnect of the redis connections

2021-05-04 08:28 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +const DefaultConsumerGroup = "-consumer-group"
Redis only provides the basic functions like set, delete, create and async comm is a library which provides your business login so in future if you decided to go ahead with a different message broker you just need to use the same functions with changing business logic

2021-05-04 08:29 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +}
Will DeleteStream() only flush the message, but stream will still exists and consumer group will also exist? FlushQ is supposed to just clean any messages which are present in the Q, but Q will remain existing in the system and the corresponding ConsumerGrp should also remain in the system so that producer can keep posting to the Q without calling CreateQ.

2021-05-04 08:29 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +}
SetKey is required for registering the consumers on initial connect and SetKey is a business logic function which can call any functions for other message broker

2021-05-04 08:30 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) PendingMessages(q string) (map[string][]string, error) {
Can you also return the count of total messages being returned as another return.

2021-05-04 08:37 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) Push(q string, msg []byte) (string, error) {
yes

2021-05-04 08:38 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +}
During the testing I found out some issues with redis lib which needs some tweaks during initialization time based on your redis server so I have provided the option to give directly with broker options

2021-05-04 08:40 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +	rdb := redis.NewRdb(ctx, opts.Redis.Host, opts.Redis.Port, opts.Redis.Username, opts.Redis.Password, log)
our application should only be aware of async comm as this is our library, main.go doesn't need to know which broker we are using at the backend

2021-05-04 08:42 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +	}
yes It requires a message before creating the group and this message will be ignored by the groups created.

2021-05-04 08:45 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) PendingMessages(q string) (map[string][]string, error) {
so it should return PendingMessages (q string) (messages, count, error)

2021-05-04 08:47 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +}
yes as long as group exits it keeps on recreating the stream so in this case it's just flushing the messages and redis doesn't provide any functions to just flush the redis stream

2021-05-04 08:47 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) CreateQ(q string) error {
In redis by default persistence will give an error

2021-05-04 12:17 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +
I can't see GetQStats() that can provide a kind of summary for a Queue.

2021-05-04 12:18 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) GroupExits(q string) bool {
Typo - change to GroupExists

2021-05-04 12:19 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +	return exits
Typo - change exits to exists

2021-05-04 12:21 UTC, kiran-anand14 commented on pkg/redis/redis.go
> +		return "", err
Add error log. Check for all such places. No error should be missed anywhere in the code.

2021-05-04 12:30 UTC, kiran-anand14 commented on pkg/redis/redis.go
> +
I don't see Appendix A implementation. asynccomm.go should create routine when a consumer calls RegisterConsumer function. This routine will keep calling a function (say RefreshConsumer()) implemented in redis.go periodically. RefreshConsumer() will keep refreshing the TTL. All this is defined in Appendix A, we discussed it, please check again.

2021-05-04 12:50 UTC, kiran-anand14 commented on pkg/redis/redis.go
> +	}
Why these loops, you have already provided Count as 1 in args?

2021-05-04 12:55 UTC, kiran-anand14 requested changes
Still reviewing, but I think you have a look at the comments added till now.

2021-05-04 13:27 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +const DefaultConsumerGroup = "-consumer-group"
I want to abstract asynccomm library from such details which are specific to Redis. When we have redis.go, so all the Redis specific terms must go in that file.

2021-05-04 13:29 UTC, kiran-anand14 commented on build/package/asynccommtest/Dockerfile
> +COPY ../../../config.yml /etc/async-comm
ok, thanks. Also, start writing ReadMe as mentioned in deliverables section which will give a basic idea that how to run everything.

2021-05-04 13:30 UTC, kiran-anand14 commented on pkg/asynccomm/ac_logger/formatter.go
> +package ac_logger
thanks.

2021-05-04 13:32 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +	rdb := redis.NewRdb(ctx, opts.Redis.Host, opts.Redis.Port, opts.Redis.Username, opts.Redis.Password, log)
So, CreateQ, Push and Pull, basically all the functions of asynccomm package that are being used to interact with the queuing system, return appropriate error that Messaging System is not up and running.

2021-05-04 13:38 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +	rdb := redis.NewRdb(ctx, opts.Redis.Host, opts.Redis.Port, opts.Redis.Username, opts.Redis.Password, log)
Nope, little disconnect. Application (asynccommtest) is the orchestrator, it knows which entities it needs to initialize, but for all the message queuing related functionality it calls functions of asynccomm, no other function of redis at all except the NewAC or NewAC....() (if needed). asynccomm is the package through which producers and consumers get everything done, but initialization of redis package is done in the application.

Think of it like this: An application might be using redis package for some other purpose as well, its not true that all the applications in future will use redis only for asynccomm. So think initialization of Redis is the responsibility of App or asynccomm.

2021-05-04 13:39 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +}
But which one is recommended to be used out of these two?

2021-05-04 13:42 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +}
Your assumption is wrong, this is not a business logic...it is only needed by redis, other message broker may have some other way or no refresh mechanism might be needed at all. Again look at my comment.

2021-05-04 13:42 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) Push(q string, msg []byte) (string, error) {
ok

2021-05-04 13:43 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) CreateQ(q string) error {
So, return the error if persistence is not possible and a user requests it on calling CreateQ, but do add the argument.

2021-05-04 13:48 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +}
Aha, that is interesting, just double check it. If it works, then I am fine.

2021-05-04 13:48 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +	}
Do you mean to say that message will always be stuck in the Q?

2021-05-04 13:49 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) PendingMessages(q string) (map[string][]string, error) {
Yes

2021-05-04 13:50 UTC, kiran-anand14 reviewed
Added replies to your queries.

2021-05-04 13:58 UTC, kiran-anand14 commented on build/package/asynccommtest/docker-compose.yml
> +    image: docker.io/parvez0/asynccomm
Don't add them on public repos, use a local docker registry or just load docker images on your host.

2021-05-04 14:02 UTC, kiran-anand14 commented on go.mod
> +	github.com/imdario/mergo v0.3.12
Is mergo a popular package? Its having v0.3.12, is it stable enough to be used?

2021-05-04 14:06 UTC, kiran-anand14 commented on internal/app/asynccommtest/main.go
> +	p_aclib, err := asynccomm.NewAC(context.TODO(), acOpts)
Why two connections with Redis? An app should have only one single connection with Redis, not different connections for producers and consumers it will initialize. Or do you have any argument for having multiple connections?

2021-05-04 14:10 UTC, kiran-anand14 commented on internal/app/asynccommtest/src/config.go
> +package src
Why src package? You can keep all the files in src/ directory in same folder where main.go is placed and all the files can be part of package main. Is it not advisable?

2021-05-04 14:13 UTC, kiran-anand14 commented on internal/app/asynccommtest/src/config.go
> +	mutex := sync.Mutex{}
What is the need of having mutex?

2021-05-04 14:15 UTC, kiran-anand14 commented on internal/app/asynccommtest/src/consumer.go
> +func (a *App) RegisterConsumer(ctx context.Context, r Routine, wg *sync.WaitGroup)  {
RegisterConsumer should be provided by asynccomm, it is clear there in the document, why app is implementing it. Read my all comments for asyncomm and redis package first, then probably you will get idea that why I am insisting on this.

2021-05-04 14:19 UTC, kiran-anand14 commented on internal/app/asynccommtest/src/consumer.go
> +			}
As mentioned in library related comments, this part of code is implemented under Pull(). It is not part of application. asynccomm library's Pull API should be self sufficient, though further it will be calling redis.go's functionality to achieve this. But the point is that we cannot burden application with these logics, application should only implement business logic, not that how it will claim messages from Q, it just need to call Pull() and it should get a message.

2021-05-04 14:22 UTC, kiran-anand14 commented on internal/app/asynccommtest/src/logger.go
> +var mutex = sync.Mutex{}
Why is mutex needed. Check whole code and see if you need mutex anywhere. I don't think you need it.

2021-05-04 14:25 UTC, kiran-anand14 commented on internal/app/asynccommtest/src/model.go
> +	return fmt.Sprintf("%d-%02d-%02dT%02d:%02d:%02d", t.Year(), t.Month(), t.Day(), t.Hour(), t.Minute(), t.Second())
If you message format in the document, it includes milliseconds as well.

2021-05-04 14:27 UTC, kiran-anand14 commented on internal/app/asynccommtest/src/producer.go
> +				a.log.Debugf("messaged pushed generated  { q: %s, id: %s }", ru.Q, res)
Change this log to "Posting <Actual Message byte array (in string) that is being posted in queue>" as given in the document.

2021-05-04 14:28 UTC, kiran-anand14 requested changes
Added more comments.

2021-05-04 16:15 UTC, parvez0 commented on internal/app/asynccommtest/src/producer.go
> +				a.log.Debugf("messaged pushed generated  { q: %s, id: %s }", ru.Q, res)
It is same check line number 28 a.log.Infof("Posting %s", msg)

2021-05-04 23:46 UTC, parvez0 commented on internal/app/asynccommtest/src/model.go
> +	return fmt.Sprintf("%d-%02d-%02dT%02d:%02d:%02d", t.Year(), t.Month(), t.Day(), t.Hour(), t.Minute(), t.Second())
added missing millisec this is the output

time="2021-05-05T00:27:25+05:30" level=info msg="Posting TestCase-app_test_producer-05:05:00:27:25.579"
time="2021-05-05T00:27:26+05:30" level=info msg="Pulled TestCase-app_test_producer-05:05:00:27:25.579 at 05:05:00:27:26.818 by app_test_consumer"
time="2021-05-05T00:27:26+05:30" level=info msg="Time TestCase-app_test_producer-05:05:00:27:25.579 remained in the Queuing System: 1818ms"
time="2021-05-05T00:27:26+05:30" level=info msg="Processing over for TestCase-app_test_producer-05:05:00:27:25.579 at 05:05:00:27:26.926"

2021-05-04 23:47 UTC, parvez0 commented on internal/app/asynccommtest/src/logger.go
> +var mutex = sync.Mutex{}
A lot of goroutines will be accessing this logger to avoid race condition mutex is required

2021-05-04 23:49 UTC, parvez0 commented on internal/app/asynccommtest/src/consumer.go
> +			}
It's been added to library pull function, code is refactored to this 
`func (a *App) InitiateConsumers(ctx context.Context, r Routine, wg *sync.WaitGroup)  {
	defer wg.Done()
	for {
		select {
		case <-ctx.Done():
			a.log.Warnf("sigterm received, safely stopping consumer '%s'", r.Name)
			return
		default:
			msg, id,  err := a.aclib.Pull(ctx, r.Q, r.Name, r.RefreshTime)
			if err != nil {
				a.log.Errorf("failed to consume message: { stream: %s, consumer: %s, error: %s }", r.Q, r.Name, err.Error())
			} else {
				sMsg := string(msg)
				msgTime := time.Now()
				if msgParts := strings.Split(sMsg, "-"); len(msgParts) > 1 {
					msgTime = GetTimeFromString(msgParts[2])
				}
				timeTaken := time.Now().Sub(msgTime)
				a.log.Infof("Pulled %s at %s by %s", sMsg, GetCurTime(), r.Name)
				a.log.Infof("Time %s remained in the Queuing System: %dms", sMsg, timeTaken.Milliseconds())
				time.Sleep(time.Duration(r.ProcessingTime) * time.Millisecond)
				if id != "" || r.Name != os.Getenv("TEST_CONSUMER") {
					err = a.aclib.Ack(r.Q, id)
					if err != nil {
						a.log.Errorf("failed to ack message %s by consumer %s : %s", id, r.Name, err.Error())
					}
					a.log.Infof("Processing over for %s at %s", sMsg, GetCurTime())
					a.log.Infof("Total Time taken for processing %s: %dms", sMsg, time.Now().Sub(msgTime))
				}
			}
		}
	}
}`

2021-05-04 23:51 UTC, parvez0 commented on internal/app/asynccommtest/src/config.go
> +	mutex := sync.Mutex{}
to avoid race condition there might be multiple go routines trying to access it

2021-05-04 23:51 UTC, parvez0 commented on internal/app/asynccommtest/src/config.go
> +package src
moved all files to main package

2021-05-04 23:53 UTC, parvez0 commented on internal/app/asynccommtest/main.go
> +	p_aclib, err := asynccomm.NewAC(context.TODO(), acOpts)
during the testing, I found out that as the number of consumers increasing in number producer was facing a deadlock issue, the consumer was waiting for a new message and was not stopping the connection. This is an issue with their library I have raised concern on their discord channel but they are not replying so it is better to have separate connections for producers and consumers

2021-05-04 23:54 UTC, parvez0 commented on go.mod
> +	github.com/imdario/mergo v0.3.12
Yes, and it has only 3 to 4 which is used to merge two different structs

2021-05-04 23:55 UTC, parvez0 commented on build/package/asynccommtest/docker-compose.yml
> +    image: docker.io/parvez0/asynccomm
it was not added tag was used only for testing on the local machine, this was never pushed to repo

2021-05-04 23:57 UTC, parvez0 commented on pkg/redis/redis.go
> +	}
yes this is the format that redis is giving us while returning the messages

[]XPackates{ []Messages: { key, value }, Stream: "", []Messages: {}, Stream: "" }

2021-05-04 23:59 UTC, parvez0 commented on pkg/redis/redis.go
> +
DeRegisterConsumer is not implemented nither redis provides functionality to delete specific consumer

2021-05-05 00:00 UTC, parvez0 commented on pkg/redis/redis.go
> +		return "", err
it is returning that error directly to the handler function so there is no need to add an extra log here

2021-05-05 00:04 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +	return exits
fixed

2021-05-05 00:04 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) GroupExits(q string) bool {
changed

2021-05-05 00:06 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +
yes need this information will integrate it let me know what else do you need in this and also this will be returning as map[string]string not as json string

2021-05-05 00:06 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) PendingMessages(q string) (map[string][]string, error) {
done

2021-05-05 00:07 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) CreateQ(q string) error {
func (ac *AsyncComm) CreateQ(q string, persistent bool) error {

2021-05-05 00:08 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +	}
I found another function which is creating the q with the group if it doesn't exits so that message is removed now

2021-05-05 00:10 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +}
if you want simple integration with minimum configuration use NewAC and if you want to handle broker configuration as well use NewACWithBrokerOptions essentially you will need to pass redis.Options{} object from application to asynclib in second case

2021-05-05 00:19 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +	rdb := redis.NewRdb(ctx, opts.Redis.Host, opts.Redis.Port, opts.Redis.Username, opts.Redis.Password, log)
1.  So you mean to say we will pass redisconn to NewAc(rdb Conn) and NewAc will just have specified functions.
2. If redis will be initialized in main, then redis package from asynccomm lib will be imported to application (currently only asynccomm is imported)
the code will look something like this 

`
function main() {
       rdb := redis.NewRdb(ctx, opts.Redis.Host, opts.Redis.Port, opts.Redis.Username, opts.Redis.Password)
      aclib := NewAc(rdb)
      app := NewApp(aclib)
}
`
let me know if this is correct or if I am still missing something

2021-05-05 00:20 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +}
removed from here

2021-05-05 05:08 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +}
Ok, I will see in the next pull request.

2021-05-05 05:14 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +	rdb := redis.NewRdb(ctx, opts.Redis.Host, opts.Redis.Port, opts.Redis.Username, opts.Redis.Password, log)
Its correct: rdb := redis.NewRdb(ctx, opts.Redis.Host, opts.Redis.Port, opts.Redis.Username, opts.Redis.Password) aclib := NewAc(rdb)

app is initializing redis first and then passing its handle to the asynccomm during asynccomm's init.

2021-05-05 05:16 UTC, kiran-anand14 commented on build/package/asynccommtest/docker-compose.yml
> +    image: docker.io/parvez0/asynccomm
Ok. I hope you its clear that you cannot make the source code, or any doc etc. public in future as well.

2021-05-05 05:16 UTC, kiran-anand14 commented on go.mod
> +	github.com/imdario/mergo v0.3.12
Ok

2021-05-05 05:31 UTC, kiran-anand14 commented on internal/app/asynccommtest/main.go
> +	p_aclib, err := asynccomm.NewAC(context.TODO(), acOpts)
Few questions:

1. What happens if there are 2 producers and 2 consumers in a single Docker container working on same queue? Does your code work?
2. Create 4 consumers in a single docker app consuming 2 different queues. Don't create any producer in the system for these queues. Does all consumers block on Pull() function call successfully? If so, then bring up another Docker container and start 2 producers producing messages for the queues. Does consumers start consuming messages fairly after producers come up in the system? One more thing, keep processing time in consumer to be 5 seconds when you create consumers.
3. And what is the significance of pools in the following snippet?
	rdbOpts := &redis.Options{
		Addr: ":6379",
		PoolSize: 100,

2021-05-05 05:31 UTC, kiran-anand14 commented on internal/app/asynccommtest/src/config.go
> +package src
Ok, thanks.

2021-05-05 05:36 UTC, kiran-anand14 commented on internal/app/asynccommtest/src/logger.go
> +var mutex = sync.Mutex{}
Why each routine will have separate logger? asynccommtest is an app, it can have multiple producer and consumer routines, but why can't they use a single logger instance? Does your code create separate loggers for each producer and consumer?

2021-05-05 05:46 UTC, kiran-anand14 commented on internal/app/asynccommtest/src/model.go
> +	return fmt.Sprintf("%d-%02d-%02dT%02d:%02d:%02d", t.Year(), t.Month(), t.Day(), t.Hour(), t.Minute(), t.Second())
Overall looks fine, but couple of questions and corrections:
1. time="2021-05-05T00:27:26+05:30" level=info msg="Processing over for TestCase-app_test_producer-05:05:00:27:25.579 at 05:05:00:27:26.926" - How much was the processing time of a message for the consumer?
2. time="2021-05-05T00:27:26+05:30" level=info msg="Time TestCase-app_test_producer-05:05:00:27:25.579 remained in the Queuing System: 1818ms" - 1818 sec is not correct if you subtract 05:05:00:27:25.579 from 05:05:00:27:26.818 i.e. it should be 1239 ms.
3. Even 1239 ms in above calculation for one single message to be pulled from a queue is too much. With what rate producers were pushing messages in the Queue and how many consumers were there? To get an idea about actual timing, can you try with one producer pushing message in Q every 1 sec and a single consumer consuming messages, then how much time is being taken in delivering the message? And then what is average time you get if producer pushes message every 10 ms?

2021-05-05 05:49 UTC, kiran-anand14 commented on internal/app/asynccommtest/src/producer.go
> +				a.log.Debugf("messaged pushed generated  { q: %s, id: %s }", ru.Q, res)
Thanks, I missed it.

Change 31 to "Failed Posting Message <actual-msg>"
Change 33 to "Posted <actual-msg> Successfully"

2021-05-05 07:18 UTC, parvez0 commented on internal/app/asynccommtest/src/logger.go
> +var mutex = sync.Mutex{}
it's not a separate logger it uses the same one that's the problem, all routines will try to access the same logger and config object

2021-05-05 07:21 UTC, parvez0 commented on internal/app/asynccommtest/src/model.go
> +	return fmt.Sprintf("%d-%02d-%02dT%02d:%02d:%02d", t.Year(), t.Month(), t.Day(), t.Hour(), t.Minute(), t.Second())
1. time is the next message as mentioned in the document.
2. Will look into it so Golang doesn't provide any functionality to calculate milliseconds we have to do it manually
3. This test was conducted over 2 sec for a producer the test files are there for this testing

2021-05-05 07:22 UTC, parvez0 commented on internal/app/asynccommtest/src/producer.go
> +				a.log.Debugf("messaged pushed generated  { q: %s, id: %s }", ru.Q, res)
should I log the error or just the mention message

2021-05-05 07:23 UTC, parvez0 commented on internal/app/asynccommtest/src/consumer.go
> +func (a *App) RegisterConsumer(ctx context.Context, r Routine, wg *sync.WaitGroup)  {
fixed

2021-05-05 07:25 UTC, parvez0 commented on internal/app/asynccommtest/main.go
> +	p_aclib, err := asynccomm.NewAC(context.TODO(), acOpts)
1. Already tested with multiple producers they can push data to the same q
2. Yes they are consuming will be blocked until a new message is available and if the q is not created they will keep on throwing the error.
3. PoolSize is the number of connections a Redis connection creates and it gets reused by other processes

2021-05-05 07:44 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +}
Then let us one single option which provides full options.

2021-05-05 07:44 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) CreateQ(q string) error {
ok, thanks.

2021-05-05 07:45 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +	}
ok, thanks

2021-05-05 07:51 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +
I am fine with the map. Can you elaborate a bit about map containing queue, number of messages in it and number of consumers. You can add other relevant stuff that Redis provides in XINFO, point is to give a way to observe the queues and this observability will also be helpful in debugging the system.

2021-05-05 07:51 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) GroupExits(q string) bool {
ok

2021-05-05 07:51 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +	return exits
ok

2021-05-05 07:53 UTC, kiran-anand14 commented on pkg/redis/redis.go
> +		return "", err
Yea, I understand, but I need error trace right at the point where error originated.

2021-05-05 07:57 UTC, kiran-anand14 commented on pkg/redis/redis.go
> +
Its fine if we don't implement DeRegister, but my comments in first para needs code changes.

2021-05-05 07:58 UTC, kiran-anand14 commented on pkg/redis/redis.go
> +	}
Ok

2021-05-05 08:04 UTC, kiran-anand14 commented on internal/app/asynccommtest/main.go
> +	p_aclib, err := asynccomm.NewAC(context.TODO(), acOpts)
For #3, do you mean to say reused by other routines in the same process? And if there are multiple connections created on calling NewAC(), then why is there a need to call NewAC separately for consumers?

Can you point me to any stackoverflow or any other link where people have faced such issue? What I believe is that there is some problem on our side in using the redis client in correct way, do study and google a bit on it. Separate NewAC() call for producers and consumers doesn't make sense to me.

2021-05-05 08:05 UTC, kiran-anand14 commented on internal/app/asynccommtest/src/consumer.go
> +func (a *App) RegisterConsumer(ctx context.Context, r Routine, wg *sync.WaitGroup)  {
ok

2021-05-05 09:11 UTC, kiran-anand14 commented on internal/app/asynccommtest/src/consumer.go
> +			}
Ok, its difficult to read from here. I will check in the next pull request.

2021-05-05 09:22 UTC, kiran-anand14 commented on internal/app/asynccommtest/src/logger.go
> +var mutex = sync.Mutex{}
You are using this mutex in initializer function which should be called only in main.go at init time. How are different routines coming into picture at initialization time of Application? From the main() function, you will initialize it once and that is it.

2021-05-05 09:29 UTC, kiran-anand14 commented on internal/app/asynccommtest/src/model.go
> +	return fmt.Sprintf("%d-%02d-%02dT%02d:%02d:%02d", t.Year(), t.Month(), t.Day(), t.Hour(), t.Minute(), t.Second())
In #1, I am asking for processing_time configured for this consumer. 2nd log message is just giving you the time it stayed in Redis. 3rd log message is giving you the total time a message remained in the system: Time a Msg spent in Redis + Time taken by Consumer to process a message (which is governed by processing_time in our consumers).

For, #2, it should be doable.

Can you provide the numbers that I have asked in point #3. I am fine with that first you finalized the code and then do testing.

2021-05-05 09:31 UTC, kiran-anand14 commented on internal/app/asynccommtest/src/producer.go
> +				a.log.Debugf("messaged pushed generated  { q: %s, id: %s }", ru.Q, res)
Failed Posting <actual-message>
Posted <actual-message> Successfully.

2021-05-05 14:01 UTC, parvez0 commented on internal/app/asynccommtest/src/consumer.go
> +func (a *App) RegisterConsumer(ctx context.Context, r Routine, wg *sync.WaitGroup)  {
registerConsumer is move to library this is how it is being called now

		case "consumer":
			wg.Add(2)
			// registering consumer with keep alive at every r.RefreshTime interval
			go cApp.aclib.RegisterConsumer(ctx, r.Name, r.RefreshTime, wg)
			go cApp.InitiateConsumers(ctx, r, wg)

2021-05-06 01:25 UTC, parvez0 commented on internal/app/asynccommtest/src/producer.go
> +				a.log.Debugf("messaged pushed generated  { q: %s, id: %s }", ru.Q, res)
if we just log the message you will not know why that failed should I do this 

ERROR: same message shown on the commit
INFO: Failed Posting <actual-message>

2021-05-06 01:30 UTC, parvez0 commented on internal/app/asynccommtest/main.go
> +	p_aclib, err := asynccomm.NewAC(context.TODO(), acOpts)
No there is no StackOverflow ticket was created for this issue so whenever the consumer is starting before the producer it's blocking the connection waiting for the message which is, in turn, blocking the producer from creating any new message hence creating a deadlock (in a single connection term)

2021-05-06 01:31 UTC, parvez0 commented on build/package/asynccommtest/docker-compose.yml
> +    image: docker.io/parvez0/asynccomm
yes

2021-05-06 01:31 UTC, parvez0 commented on pkg/redis/redis.go
> +
pushed the changes in latest commit

2021-05-06 01:32 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +
ok will look into it

2021-05-06 10:36 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) ClaimPendingMessages(q, consumer string) error {
moved to Pull

2021-05-06 10:42 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +	return nil
made the change

2021-05-06 10:43 UTC, parvez0 commented on internal/app/asynccommtest/src/logger.go
> +var mutex = sync.Mutex{}
tried without it was working fine so removed mutex

2021-05-06 10:44 UTC, parvez0 commented on internal/app/asynccommtest/src/config.go
> +	mutex := sync.Mutex{}
removed

2021-05-07 13:35 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +func (ac *AsyncComm) ClaimPendingMessages(q, consumer string) error {
ok

2021-05-07 14:20 UTC, parvez0 commented on internal/app/asynccommtest/src/producer.go
> +				a.log.Debugf("messaged pushed generated  { q: %s, id: %s }", ru.Q, res)
implemented

2021-05-07 14:21 UTC, parvez0 commented on internal/app/asynccommtest/src/logger.go
> +var mutex = sync.Mutex{}
closed

2021-05-07 14:21 UTC, parvez0 commented on internal/app/asynccommtest/src/consumer.go
> +			}
closed

2021-05-07 14:21 UTC, parvez0 commented on pkg/redis/redis.go
> +
closed

2021-05-07 14:21 UTC, parvez0 commented on pkg/redis/redis.go
> +		return "", err
closed

2021-05-08 10:17 UTC, kiran-anand14 commented on internal/app/asynccommtest/config.go
> +	ClaimTime int      `json:"claim_time" mapstructure:"claim_time"`
ClaimTime is only applicable to consumers. And one more thing, every can have a different ClaimTime, so its better to include it in Routine struct and have a consumer act on the basis of claim time set specifically for it.

2021-05-08 10:21 UTC, kiran-anand14 commented on internal/app/asynccommtest/config.go
> +	viper.SetDefault("redis.port", "3306")
Isn't default Redis port 6379?

2021-05-08 10:40 UTC, kiran-anand14 commented on internal/app/asynccommtest/consumer.go
> +			msg, id,  err := a.aclib.Pull(r.Q, r.Name, 100 * time.Millisecond)
What is the purpose of third argument i.e. block in this function call? I know you are using it for XREADGROUP. Even if you want to use it, let us treat like refreshTime, claimTime etc.

2021-05-08 10:51 UTC, kiran-anand14 commented on internal/app/asynccommtest/main.go
> +	InitializeLogger(cnf)
Can't these return any error? Suppose if a user doesn't provide some mandatory parameters in the configuration?

This init() is not being called from anywhere in the code? Am I missing some files?

InitializeConfig() is also not being called from anywhere other than a test file, if this is only for testing then it should be moved to test file.

2021-05-08 11:05 UTC, kiran-anand14 commented on internal/app/asynccommtest/main.go
> +			go pApp.aclib.RegisterConsumer(ctx, r.Name, r.RefreshTime, cnf.App.ClaimTime, wg)
asynccomm library (package) will create a go routine for refreshing a consumer, application will not create go routine. If N consumers had called RegisterConsumer(), then asynccomm library will refresh these N consumers in a separate go routine. Always remember it is not an application's business logic to refresh a consumer, application should not be burdened with the task of refreshing a consumer by running it as routine, app will simply call library function RegisterConsumer() and tell the refresh time and after that, library handles refreshing for consumers.

2021-05-08 11:11 UTC, kiran-anand14 commented on internal/app/asynccommtest/consumer.go
> +				time.Sleep(time.Duration(r.ProcessingTime) * time.Millisecond)
Go to sleep only if an actual message is returned by Pull(), i.e. when you are sure that its a valid message and you are going to call Ack() for this message after processing (i.e. sleep) is over.

2021-05-08 11:14 UTC, kiran-anand14 commented on internal/app/asynccommtest/consumer.go
> +				if id != "" || r.Name != os.Getenv("TEST_CONSUMER") {
Are you hitting this conditions when id is "", why would it happen?

And what is the significance of r.Name != os.Getenv("TEST_CONSUMER")?

2021-05-08 11:16 UTC, kiran-anand14 commented on internal/app/asynccommtest/consumer.go
> +						a.log.Errorf("failed to ack message %s by consumer %s : %s", id, r.Name, err.Error())
What can be the reason of getting error on trying to send ack for a message?

2021-05-08 12:20 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +	ClaimTime int
claimTime, refreshTime and blockTime (if you think is needed), all per consumer. So every asynccomm library should maintain these timers in a consumer struct. asynccomm library will maintain list of consumers. Consumer element will be created and added in this list when RegisterConsumer() is called by a consumer.

As I said earlier as well, on similar lines to RegisterConsumer(), asynccomm should provide DeRegisterConsumer() in which this the consumer will be deleted from list and routine sending periodic refresh requests for the consumer will be stopped.

2021-05-08 14:36 UTC, kiran-anand14 commented on pkg/redis/redis.go
> +		MinIdle:   20000,
Don't give MinIdle field here, you are providing the msgId. Again, check Appendix A in the document:
_XCLAIM \<stream\> \<consumer-group\> \<name-of-consumer-claiming-the-pending-message\> \<msg-id-found-from-XPENDING-output\>_

2021-05-08 14:45 UTC, kiran-anand14 commented on pkg/redis/redis.go
> +			r.Log.Debugf("messages claimed! { inActiveConsumer: %s, newConsumer: %s }", k, consumer)
A consumer can claim only message at a time. So, as soon as it successfully claims a message, it should return from this function. Other consumers may be free and be able to reclaim messages.

2021-05-08 14:56 UTC, kiran-anand14 commented on pkg/redis/redis.go
> +	}
What is this code doing? only XAck() should be sufficient, right?

2021-05-08 14:57 UTC, kiran-anand14 requested changes
I am pulling your changes, but I have added more comments. Please work on them and send pull request again.

2021-05-08 14:58 UTC, merged

2021-05-09 23:55 UTC, parvez0 commented on pkg/redis/redis.go
> +	}
For keeping track of ack messages for this consumer we have to use it redis doesn't provide a way to get the number of ack messages

2021-05-10 00:22 UTC, parvez0 commented on pkg/redis/redis.go
> +		if _, err := r.Get("active_consumers_" + k); err != nil {
Yes, that's what I am checking there first I am trying to get the consumer using r.Get() if the error is not nil then it means that the key is doesn't exits and also if the connection breaks the consumer will not be able to claim the message. If you want me to check only for key doesn't exits error then I can do string match

2021-05-10 00:23 UTC, parvez0 commented on pkg/redis/redis.go
> +		MinIdle:   20000,
This min idle time is required to stop all the consumers from trying to consume the same message from a dead consumer.

2021-05-10 00:25 UTC, parvez0 commented on pkg/redis/redis.go
> +	msgs, _, err := r.PendingStreamMessages(q)
where will I get the msgIdleDuration time from? will you be providing or should I hardcode

2021-05-10 00:29 UTC, parvez0 commented on internal/app/asynccommtest/model.go
> +type ProducerMessage struct {
Changed

2021-05-10 00:29 UTC, parvez0 commented on internal/app/asynccommtest/consumer.go
> +						a.log.Errorf("failed to ack message %s by consumer %s : %s", id, r.Name, err.Error())
Connection break

2021-05-10 00:32 UTC, parvez0 commented on internal/app/asynccommtest/consumer.go
> +				if id != "" || r.Name != os.Getenv("TEST_CONSUMER") {
yes, Id is null if the consumer doesn't get any messages. we are still continuing the process if we don't get any message.

r.Name != os.Getenv("TEST_CONSUMER") this is a testing code to stimulate a consumer going down, if we give the consumer name here it will not let it ack the message which would then be consumed by other consumers

2021-05-10 00:33 UTC, parvez0 commented on internal/app/asynccommtest/consumer.go
> +				time.Sleep(time.Duration(r.ProcessingTime) * time.Millisecond)
You mentioned to continue with the flow if no messages were fetched can you confirm on this once again

2021-05-10 00:35 UTC, parvez0 commented on internal/app/asynccommtest/main.go
> +			go pApp.aclib.RegisterConsumer(ctx, r.Name, r.RefreshTime, cnf.App.ClaimTime, wg)
So are you saying that main application will call using only pApp.aclib.RegisterConsumer and it should create a go routine internally

2021-05-10 00:39 UTC, parvez0 commented on internal/app/asynccommtest/main.go
> +	InitializeLogger(cnf)
These are the initial mandatory configuration so if any error occurs it's automatically exiting with panic.

init() gets automatically called before calling Main()

initializeConfig() is being called in the main file of the application right. It's the major component which holds all the configuration provided if we don't initialize it the application will not work

2021-05-10 00:42 UTC, parvez0 commented on internal/app/asynccommtest/consumer.go
> +			msg, id,  err := a.aclib.Pull(r.Q, r.Name, 100 * time.Millisecond)
So block time is the min time a consumer should wait for a message to be available, if we don't provide it the consumers are doing a lot of unnecessary calls to check the message availability.

Yes will create a ConsumerOptions which holds all of this data and will be used in register consumer

2021-05-10 00:43 UTC, parvez0 commented on internal/app/asynccommtest/config.go
> +	viper.SetDefault("redis.port", "3306")
yes, I was playing around with it and forgot to change it. It fixed

2021-05-10 00:43 UTC, parvez0 commented on internal/app/asynccommtest/config.go
> +	ClaimTime int      `json:"claim_time" mapstructure:"claim_time"`
It will be an Field in the ConsumerType will be passed to RegisterConsumer

2021-05-10 03:34 UTC, parvez0 commented on pkg/redis/redis.go
> +		MinIdle:   20000,
can be rectified from the resolution of previous comment

2021-05-10 04:33 UTC, parvez0 commented on pkg/asynccomm/asynccomm.go
> +	ClaimTime int
Implemented 
RegisterConsumer(c Consumer) error // it will create syncConsumer routine internally
DeRegisterConsumer(consumer string) error // it will release all the resources held by this consumer

2021-05-10 04:34 UTC, parvez0 commented on internal/app/asynccommtest/main.go
> +			go pApp.aclib.RegisterConsumer(ctx, r.Name, r.RefreshTime, cnf.App.ClaimTime, wg)
it's implemented

2021-05-10 04:35 UTC, parvez0 commented on internal/app/asynccommtest/consumer.go
> +			msg, id,  err := a.aclib.Pull(r.Q, r.Name, 100 * time.Millisecond)
it's implemented

2021-05-10 05:48 UTC, kiran-anand14 commented on internal/app/asynccommtest/config.go
> +	ClaimTime int      `json:"claim_time" mapstructure:"claim_time"`
ok

2021-05-10 05:48 UTC, kiran-anand14 commented on internal/app/asynccommtest/config.go
> +	viper.SetDefault("redis.port", "3306")
ok

2021-05-10 05:50 UTC, kiran-anand14 commented on internal/app/asynccommtest/main.go
> +	InitializeLogger(cnf)
Understood.

2021-05-10 05:51 UTC, kiran-anand14 commented on internal/app/asynccommtest/main.go
> +			go pApp.aclib.RegisterConsumer(ctx, r.Name, r.RefreshTime, cnf.App.ClaimTime, wg)
> So are you saying that main application will call using only pApp.aclib.RegisterConsumer and it should create a go routine internally

Yes...

2021-05-10 05:52 UTC, kiran-anand14 commented on internal/app/asynccommtest/consumer.go
> +				time.Sleep(time.Duration(r.ProcessingTime) * time.Millisecond)
Sleeping of a consumer represents the processing time it is taking for processing a message, if message was not pulled at all from the queue, then what is the point of sleeping. I hope it clarifies.

2021-05-10 06:08 UTC, kiran-anand14 commented on internal/app/asynccommtest/consumer.go
> +				if id != "" || r.Name != os.Getenv("TEST_CONSUMER") {
Ok.

2021-05-10 06:09 UTC, kiran-anand14 commented on internal/app/asynccommtest/consumer.go
> +						a.log.Errorf("failed to ack message %s by consumer %s : %s", id, r.Name, err.Error())
ok

2021-05-10 06:10 UTC, kiran-anand14 commented on internal/app/asynccommtest/model.go
> +type ProducerMessage struct {
ok

2021-05-10 06:11 UTC, kiran-anand14 commented on pkg/asynccomm/asynccomm.go
> +	ClaimTime int
Ok

2021-05-10 06:59 UTC, kiran-anand14 commented on pkg/redis/redis.go
> +	msgs, _, err := r.PendingStreamMessages(q)
You can take it also as part of configuration value per consumer.

2021-05-10 07:10 UTC, kiran-anand14 commented on pkg/redis/redis.go
> +		if _, err := r.Get("active_consumers_" + k); err != nil {
"also if the connection breaks the consumer will not be able to claim the message" - this is not true. Consumer may be running in the another docker container, its network connectivity may be up. So, you should claim a message if Get() fails but it is not failed due to network connectivity. I am sure error returned Get() should be giving you the reason that why it is failing.

2021-05-10 07:12 UTC, kiran-anand14 commented on pkg/redis/redis.go
> +	}
Why do we need to track number of messages that we acked? Is it mandated by Redis to do so?

2021-05-10 07:26 UTC, parvez0 commented on pkg/redis/redis.go
> +	msgs, _, err := r.PendingStreamMessages(q)
What should be the default idle time should I put it as 5000 ms

2021-05-10 07:28 UTC, parvez0 commented on pkg/redis/redis.go
> +		if _, err := r.Get("active_consumers_" + k); err != nil {
yes so for that I'll have to do a string match it will give an error like this "key not found" I'll just compare it

2021-05-10 15:56 UTC, parvez0 commented on internal/app/asynccommtest/consumer.go
> +				time.Sleep(time.Duration(r.ProcessingTime) * time.Millisecond)
implemented

2021-05-10 15:57 UTC, parvez0 commented on pkg/redis/redis.go
> +	msgs, _, err := r.PendingStreamMessages(q)
done the default time is 5000ms, go-redis library is not giving the option to specify idle time I am creating a pull request on their branch after making the changes, for now it is working with default settings

2021-05-10 15:58 UTC, parvez0 commented on pkg/redis/redis.go
> +		MinIdle:   20000,
Removed minIdle time from XClaim

2021-05-10 15:58 UTC, parvez0 commented on pkg/redis/redis.go
> +		if _, err := r.Get("active_consumers_" + k); err != nil {
Implemented checking for the error when key is not present

2021-05-10 15:59 UTC, parvez0 commented on pkg/redis/redis.go
> +			r.Log.Debugf("messages claimed! { inActiveConsumer: %s, newConsumer: %s }", k, consumer)
After consuming one message returning ending the claim function

2021-05-11 08:40 UTC, kiran-anand14 commented on pkg/redis/redis.go
> +		MinIdle:   20000,
Ok

2021-05-11 08:55 UTC, parvez0 commented on pkg/redis/redis.go
> +	msgs, _, err := r.PendingStreamMessages(q)
go-redis library does not provide the option to specify Idle time, I am using XPendingExt only if you take a look at the code, It doesn't have an option 

type XPendingExtArgs struct {
	Stream   string
	Group    string
	Start    string
	End      string
	Count    int64
	Consumer string
}

it only takes these arguments

2021-05-11 08:58 UTC, parvez0 commented on pkg/redis/redis.go
> +	}
With XInfo only this information will be available where you will not know the details about the ack messages 

redis.QStatus{
	Info:redis.Info{
		Length:5,                
		Acknowledged:5,          // these will be removed and all the other information will be present
		RadixTreeKeys:1, 
		RadixTreeNodes:2, 
		LastGeneratedID:"1620421718593-0", 
		Groups:1, 
		FirstEntry:redis.Message{
			ID:"1620421718588-0", 
			Values:map[string]interface {}{
				"message":"test_message_0_2021-05-08 02:38:38.562616 +0530 IST m=+0.002343927"
			}}, 
		LastEntry:redis.Message{
			ID:"1620421718593-0", Values:map[string]interface {}{
				"message":"test_message_4_2021-05-08 02:38:38.577363 +0530 IST m=+0.017090815"
			}}}, 
	Consumers:[]redis.Consumer{
		redis.Consumer{
			Name:"test_consumer1", 
			Pending:0, 
			Idle:6
		}, 
		redis.Consumer{
			Name:"test_consumer2", 
			Pending:0, 
			Idle:7
		}}, 
	Groups:[]redis.Group{
		redis.Group{
			Name:"test_queue-consumer-group", 
			Consumers:2, 
			Pending:0, 
			LastDeliveredID:"1620421718593-0"
		}
	}
}

2021-05-12 06:17 UTC, kiran-anand14 commented on pkg/redis/redis.go
> +	msgs, _, err := r.PendingStreamMessages(q)
Ok